#!/usr/bin/env Rscript
# MAGI baseline: Lynx-Hare real data (Exp8)
#
# Uses the LV model from models.R on Hudson's Bay Company data.
# Data is read from baselines/data/lynxhare.csv (generated by Exp8 Julia script).
#
# Usage:
#   Rscript baselines/magi/run_magi_lynxhare.R
#   Rscript baselines/magi/run_magi_lynxhare.R --seed 42 --niter 20000

library(magi)
library(coda)

# Source custom model definitions
get_script_dir <- function() {
  args <- commandArgs(trailingOnly = FALSE)
  file_arg <- grep("--file=", args, value = TRUE)
  if (length(file_arg) > 0) {
    return(dirname(normalizePath(sub("--file=", "", file_arg))))
  }
  tryCatch(dirname(sys.frame(1)$ofile), error = function(e) ".")
}
script_dir <- get_script_dir()
source(file.path(script_dir, "models.R"))

# ── Configuration ──────────────────────────────────────────────────────────

args <- commandArgs(trailingOnly = TRUE)

parse_arg <- function(flag, default) {
  idx <- which(args == flag)
  if (length(idx) > 0 && idx < length(args)) return(args[idx + 1])
  return(default)
}

seeds      <- as.integer(strsplit(parse_arg("--seed", "42,123,456,789,1234"), ",")[[1]])
niter_hmc  <- as.integer(parse_arg("--niter", "20000"))
nsteps_hmc <- as.integer(parse_arg("--nsteps", "200"))
burnin     <- as.numeric(parse_arg("--burnin", "0.5"))
do_trajectory <- "--trajectory" %in% args

param_names <- c("a", "b", "c", "d")

data_dir    <- file.path(script_dir, "..", "data")
results_dir <- file.path(script_dir, "results")
dir.create(results_dir, showWarnings = FALSE, recursive = TRUE)

# ── Load data ──────────────────────────────────────────────────────────────

data_file <- file.path(data_dir, "lynxhare.csv")
if (!file.exists(data_file)) {
  # Generate data inline if CSV not found
  cat("lynxhare.csv not found in data_dir. Using built-in data.\n")
  years <- 1900:1920
  hare <- c(30.0, 47.2, 70.2, 77.4, 36.3, 20.6, 18.1, 21.4, 22.0,
            25.4, 27.1, 40.3, 57.0, 76.6, 52.3, 19.5, 11.2, 7.6,
            14.6, 16.2, 24.7)
  lynx <- c(4.0, 6.1, 9.8, 35.2, 59.4, 41.7, 19.0, 13.0, 8.3,
            9.1, 7.4, 8.0, 12.3, 19.5, 45.7, 51.1, 29.7, 15.8,
            9.7, 10.1, 8.6)
  dat <- data.frame(
    time = (years - 1900) / 20,
    hare = hare / 100,
    lynx = lynx / 100
  )
} else {
  dat <- read.csv(data_file)
}

# ── Run ────────────────────────────────────────────────────────────────────

results_all <- data.frame()

for (seed in seeds) {
  # Format for MAGI
  y_obs <- data.frame(time = dat$time, prey = dat$hare, predator = dat$lynx)
  y_input <- setDiscretization(y_obs, level = 1)

  cat(sprintf("LynxHare: seed=%d, niter=%d ...\n", seed, niter_hmc))
  set.seed(seed)
  t_start <- proc.time()
  result <- MagiSolver(
    y = y_input,
    odeModel = lvmodel,
    control = list(
      niterHmc = niter_hmc,
      nstepsHmc = nsteps_hmc,
      burninRatio = burnin
    )
  )
  t_elapsed <- (proc.time() - t_start)["elapsed"]

  theta_samples <- result$theta
  theta_mean <- colMeans(theta_samples)
  theta_std  <- apply(theta_samples, 2, sd)

  # ESS
  ess_vals <- effectiveSize(theta_samples)
  ess_mean <- mean(ess_vals)
  ess_per_sec <- ess_mean / as.numeric(t_elapsed)

  cat(sprintf("  theta_mean=(%.3f, %.3f, %.3f, %.3f)  ESS_mean=%.1f  time=%.1fs\n",
              theta_mean[1], theta_mean[2], theta_mean[3], theta_mean[4],
              ess_mean, t_elapsed))

  # Summary row
  row <- data.frame(
    ode = "LynxHare", method = "MAGI", seed = seed,
    ess_mean = ess_mean, time_sec = as.numeric(t_elapsed),
    ess_per_sec = ess_per_sec
  )
  for (i in seq_along(param_names)) {
    row[[paste0("theta_", param_names[i], "_mean")]] <- theta_mean[i]
    row[[paste0("theta_", param_names[i], "_std")]]  <- theta_std[i]
    row[[paste0("ess_", param_names[i])]] <- ess_vals[i]
  }
  results_all <- rbind(results_all, row)

  # Save posterior samples
  samples_df <- as.data.frame(theta_samples)
  colnames(samples_df) <- param_names
  write.csv(samples_df,
            file.path(results_dir, sprintf("lynxhare_seed%d_samples.csv", seed)),
            row.names = FALSE)

  # Trajectory output
  if (do_trajectory && seed == seeds[1]) {
    x_samples <- result$xsampled
    x_mean  <- apply(x_samples, c(2, 3), mean)
    x_lower <- apply(x_samples, c(2, 3), quantile, 0.025)
    x_upper <- apply(x_samples, c(2, 3), quantile, 0.975)

    comp_names <- c("hare", "lynx")
    traj_df <- data.frame(t = y_input$time)
    for (k in seq_along(comp_names)) {
      traj_df[[paste0("mean_", comp_names[k])]]  <- x_mean[, k]
      traj_df[[paste0("lower_", comp_names[k])]] <- x_lower[, k]
      traj_df[[paste0("upper_", comp_names[k])]] <- x_upper[, k]
    }
    traj_fname <- file.path(results_dir, "magi_lynxhare_trajectory.csv")
    write.csv(traj_df, traj_fname, row.names = FALSE)
    cat(sprintf("  Trajectory saved to %s\n", traj_fname))
  }
}

# Save aggregated results
write.csv(results_all,
          file.path(results_dir, "magi_lynxhare_summary.csv"),
          row.names = FALSE)
cat("Results saved to", file.path(results_dir, "magi_lynxhare_summary.csv"), "\n")
